sudo: required
dist: trusty
language: cpp

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:kojoley/boost
    - sudo apt-get update -y || echo "update error"
    - lsb_release -a

install:
    - git clone https://github.com/yyzybb537/Boost-dev-bin.git /tmp/boost-dev-bin && sudo dpkg -i /tmp/boost-dev-bin/libboost1.59-all-dev.deb
    - ls /usr/local/lib/libboost*
    - sudo ldconfig
    - sudo apt-get install -y -qq cmake 

script: 
    - mkdir build; pushd build;
    - cmake .. && make -j4
    - popd;
    - pushd test/gtest_unit; mkdir build; pushd build;
    - cmake .. && make -j4 && ../runall.sh
    - popd;

after_success:
    - 

branches:
    only:
    - dev
    - 3.0
    - master

notifications:
  email: true


